#pragma once
#ifndef ZLUA
#define ZLUA
#include <glad/glad.h>
#include <GLFW/glfw3.h>
#include <stdexcept>
#include <string>
#include <vector>
#include "./Core/status.h"
#include "./Core/vec2.h"
#include "./Graphics/Shader.h"
#include "./Graphics/Materials/Colour.h"
#include "./Graphics/Materials/Material.h"
#include "./Graphics/Materials/Diffuse2D.h"
#include "./Graphics/Materials/Textured2D.h"
#include  "./Core/Mesh.h"
#include  "./Core/Scene.h"
#include  "./Core/World.h"
#include "./Core/GameObject.h"
#include "./Graphics/Renderer.h"
#include "./Behaviours/ZWorldBehaviour.h"
#include "Core/Predefined_Meshes/Rectangle.h"
#endif