#pragma once
#ifndef ZLUA
#define ZLUA
#define STB_IMAGE_IMPLEMENTATION
#include <glad/glad.h>
#include <GLFW/glfw3.h>
#include <stdexcept>
#include <string>
#include <vector>
#include "./Core/status.h"
#include "./Graphics/vec2.h"
#include "./Graphics/Shader.h"
#include "./Graphics/Materials/Colour.h"
#include "./Graphics/Materials/Material.h"
#include "./Graphics/Materials/Diffuse2D.h"
#include "./Graphics/Materials/Textured2D.h"
#include  "./Core/Mesh.h"
#include  "./Core/Scene.h"
#include  "./Core/World.h"
#endif